### ISSUE TITLE
pytz requirement outdated

### ISSUE THREAD

**Issue by FObersteiner** [aerupt/whenareyou#12]
the `pip install whenareyou` has a requirement `pytz~=2016.10` - which is totally outdated. Current version is `pytz-2021.1`.

**Comment by sils** [comment]
Hey, sadly, I can't afford to maintain this package any longer. You can make a fork if you like :)

**Comment by FObersteiner** [comment]
Yup, sorry I should read the description on the main page before posting issues ^^ [This fork](https://github.com/entvia/whenareyou) got the issue handled already.

I'll think about creating a fork anyway; might be good to change `pytz` to `zoneinfo` in the first place.

**Comment by FObersteiner** [comment]
@sils it got more like a re-write: https://github.com/MrFuppes/whenareyou - still really nice I think.

replaced:
- pytz --> zoneinfo (means it requires now Python 3.9)
- tzwhere --> timezonefinder
- google maps api --> openstreetmaps

**Comment by sils** [comment]
@MrFuppes  Delighted to see that this is happening :) Should we add a prominent link to the fork in the README?

**Comment by FObersteiner** [comment]
> 
> 
> @MrFuppes Delighted to see that this is happening :) Should we add a prominent link to the fork in the README?

yes sure :) I hope I'll be able to add some more stuff (unit tests etc.) soon.

**Comment by sils** [comment]
Done that!
